version: '3'
services:
  backend:
    restart: always
    build: .
    ports:
      - '8080:3000'
    depends_on:
      - db
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: leanjunio
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: portfolio
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - '27017:27017'
    command: mongod
