version: '3'
services:
  backend:
    restart: always
    build: .
    ports:
      - '8080:3000'
    links:
      - db
  db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
